# Generated by Django 5.1.1 on 2024-09-14 19:48

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "scientific_name",
                    models.CharField(max_length=255, verbose_name="Scientific Name"),
                ),
                (
                    "contamination_type",
                    models.CharField(
                        choices=[
                            ("INJ", "Injectable"),
                            ("ING", "Ingestible"),
                            ("INH", "Inhalable"),
                            ("CON", "Contact"),
                            ("OTH", "Other"),
                        ],
                        default="OTH",
                        max_length=3,
                        verbose_name="Contamination Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("symptoms", models.TextField(verbose_name="Symptoms")),
                ("treatment", models.TextField(verbose_name="Treatment")),
                (
                    "image",
                    models.ImageField(upload_to="poisons/imgs/", verbose_name="Image"),
                ),
                ("info_url", models.URLField(verbose_name="Info URL")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
        ),
    ]
