# Generated by Django 5.1.1 on 2024-09-14 23:36

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poisons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poison",
            name="image",
            field=models.ImageField(
                upload_to="poisons/imgs/",
                validators=[core.validators.validate_img],
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="poison",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="poison",
            name="scientific_name",
            field=models.CharField(max_length=40, verbose_name="Scientific Name"),
        ),
    ]
