# Generated by Django 5.1.1 on 2024-09-19 18:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poisons", "0002_alter_poison_image_alter_poison_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poison",
            name="description",
            field=ckeditor.fields.RichTextField(
                default="<h3>Sem Informações Adicionais</h3>",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="poison",
            name="symptoms",
            field=ckeditor.fields.RichTextField(
                default="<h3>Sem Informações Adicionais</h3>", verbose_name="Symptoms"
            ),
        ),
        migrations.AlterField(
            model_name="poison",
            name="treatment",
            field=ckeditor.fields.RichTextField(
                default="<h3>Sem Informações Adicionais</h3>", verbose_name="Treatment"
            ),
        ),
    ]
